### PR TITLE
Remove unused TypeUtils

### PR DESCRIPTION
**Pull request by Gurkenglas**

### CODE REVIEW

**Comment by lspitzner** [comment]
does not compile.. is this meant as a work-in-progress?

**Comment by Gurkenglas** [comment]
I didn't think it wouldn't typecheck. I am now in position to typecheck pull requests before I submit them. That took a while. Here, this should work?

**Comment by lspitzner** [comment]
Btw you can amend your last commit in such cases (and force-push it) as to avoid creating a non-working commit in the project's public history. (or squash, which is the same for more than 2 commits.)

**Comment by lspitzner** [comment]
oh, i can squash and merge too.. neat.

**Comment by lspitzner** [comment]
Thanks!

**Pull request merged**
